config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :requests, only: [:index, :show, :edit, :destroy]
  resources :answers, only: [:index, :show, :edit, :update, :destroy]
  resources :questions
  resources :applications
  resources :teams
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get '/teams/:id/requests/new', to: 'requests#new', as: 'new_request'
  post '/teams/:id/requests', to: 'requests#create'

  get '/sessions/new_admin_session', to: 'sessions#new_admin_session', as: 'new_admin_session'
  post '/sessions/new_admin_session', to: 'sessions#create_admin_session', as: 'admin_session'
  delete '/sessions', to: 'sessions#destroy'

  get 'teams/:id/answers/new', to: 'answers#new', as: 'new_answer'
  post '/teams/:id/answers', to: 'answers#create'
  
  get 'admins/:id/my_teams', to: 'admins#my_teams', as: 'my_teams'
end
  

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class= "login-container">
  <div class="login-form">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<p>
<%= link_to 'Show', @admin %> |
<%= link_to 'Back', @admin %>
</p>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.name %></td>
        <td><%= admin.email %></td>
        <td><%= admin.password_digest %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/my_teams.html.erb
<% @my_teams.each do |t|%>

    <div class="parent">

    <div class="div1">  <p>

    <h2><%= t.company %></h2>

    <div class="line"></div>
       
        <% t.requests.each do |r| %>
            <p>Name: <%= r.name%></p>
            <p>Age: <%= r.age%></p>
            <p>Skills: <%= r.skills%></p>
                <% r.team.questions.each do |q|%>
                <p><%= q.question_text %></p>
                <%end%>
                <!-- r.user.answers.find_by(question_id: 5).answer_input
                Question.find_by(team_id: t.id).id => 5 --> 
            <p><%= r.user.answers.find_by(question_id: Question.find_by(team_id: t.id).id).answer_input%></p>

            <div class="line">
        
            </div>
        <%end%>

    </div>

<%end%>

<h2><%= link_to "Create a Team", new_team_path %></h2>

app/views/admins/new.html.erb
<h1>New Admin</h1>
<%= render 'form', admin: @admin %>


<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'My Teams', my_teams_path %> |
<%= link_to 'Back', teams_path %>
</p>