config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :requests, only: [:index, :show, :edit, :destroy]
  resources :answers, only: [:index, :show, :edit, :update, :destroy]
  resources :questions
  resources :applications
  resources :teams
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get '/teams/:id/requests/new', to: 'requests#new', as: 'new_request'
  post '/teams/:id/requests', to: 'requests#create'

  get '/sessions/new_admin_session', to: 'sessions#new_admin_session', as: 'new_admin_session'
  post '/sessions/new_admin_session', to: 'sessions#create_admin_session', as: 'admin_session'
  delete '/sessions', to: 'sessions#destroy'

  get 'teams/:id/answers/new', to: 'answers#new', as: 'new_answer'
  post '/teams/:id/answers', to: 'answers#create'
  
  get 'admins/:id/my_teams', to: 'admins#my_teams', as: 'my_teams'
end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :requests, dependent: :destroy
    has_many :teams, through: :requests
    has_many :answers
    enum role: [:standard_user, :gold_user]
    # after_initialize :set_default_role, :if => :new_record?

    validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    has_secure_password
    has_one_attached :avatar 

    # def set_default_role
    #     self.role ||= :student
    # end


    # find answers according to team / question
    #self.answers.where(Question.find(self.question_id) == team.question)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    # @user.role = params[:user][:role]

    respond_to do |format|
      if @user.save 
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :age, :password, :role, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
    <body>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class= "login-container">
  <div class="login-form">
    <h1>Sign up!</h1>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <p>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </p>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
  <%= form.label :Membership%>
  <%= form.select(:role, options_for_select([['Standard Member', 'standard_user'], ['Gold Member', 'gold_user']]))%>
  </div>
  <div class="field">
<%= form.label "profile photo"%>
<%= form.file_field :avatar %>
</div>
  <div class="actions">
    <%= form.submit %>
  </div>
  </div>
  </div>
  
<% end %>

</body>

app/views/users/edit.html.erb
<h1>Edit your Profile</h1>

<%= render 'form', user: @user %>
<p><%= link_to 'Back', teams_path %></p

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Membership</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div>
<div class="page-container" >
<div class = "page-header">
    <h1>Join Below!</h1>
<h3> Sign up below to get access to the our amazing database of qualified professionals</h3>
</div>
</div>

<%= render 'form', user: @user %><br>

<%= link_to 'Back', users_path %><br>


</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "login-container">
  <div class= "login-form">

  <h2>Your Profile</h2>

 <p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<% if @user.avatar.attached? %>
<p><image src="<%=(url_for(@user.avatar))%>" style="max-height:150px;width:200px;"></p>

<%end%>

<p>
  <!-- <strong>Password:</strong> -->
  <% @user.password_digest %>
</p>
<br>
<p><%=link_to 'Log in to see what teams are looking! ', new_session_path %></p>

<p><%= link_to 'Edit Profile', edit_user_path(@user) %> </p>
</div>
</div>


<p><% link_to 'Login', new_session_path %></p>