config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :requests, only: [:index, :show, :edit, :destroy]
  resources :answers, only: [:index, :show, :edit, :update, :destroy]
  resources :questions
  resources :applications
  resources :teams
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get '/teams/:id/requests/new', to: 'requests#new', as: 'new_request'
  post '/teams/:id/requests', to: 'requests#create'

  get '/sessions/new_admin_session', to: 'sessions#new_admin_session', as: 'new_admin_session'
  post '/sessions/new_admin_session', to: 'sessions#create_admin_session', as: 'admin_session'
  delete '/sessions', to: 'sessions#destroy'

  get 'teams/:id/answers/new', to: 'answers#new', as: 'new_answer'
  post '/teams/:id/answers', to: 'answers#create'
  
  get 'admins/:id/my_teams', to: 'admins#my_teams', as: 'my_teams'
end
  

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :user
    belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @team_id = request.url.split('/')[4]
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
    
    @team_id = request.url.split('/')[4]
    
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_input: params[:answer_input])
    @answer.question_id = Question.find_by(team_id: request.url.split('/')[4]).id #added this to get a default team id
     @answer.user_id = session[:user_id]
    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Thank you for submitting your answer.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:answer_input, :question_id, :user_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_tag  "/teams/#{@team_id}/answers"  do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>


    </div>

  <% end %>

  <h3><%= Question.find_by(team_id: request.url.split('/')[4]).question_text%></h3>
  
  <label>Answer</label>
  <%= text_area_tag :answer_input %><br>
  
  
  <%= submit_tag "Submit answer" %>
  
  
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Answer input</th>
      <th>Question</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.answer_input %></td>
        <td><%= answer.question_id %></td>
        <td><%= answer.user_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/answers/new.html.erb
<h1>Competency test [Answer new]</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "answercontainer">
<p>
Thank you for submitting your answer
</p>

<%link_to 'Edit', edit_answer_path(@answer) %> 
<p><%= link_to 'See more teams!', teams_path %></p> 

</div>