config/routes.rb
Rails.application.routes.draw do
  resources :admins, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :requests, only: [:index, :show, :edit, :destroy]
  resources :answers, only: [:index, :show, :edit, :update, :destroy]
  resources :questions
  resources :applications
  resources :teams
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get '/teams/:id/requests/new', to: 'requests#new', as: 'new_request'
  post '/teams/:id/requests', to: 'requests#create'

  get '/sessions/new_admin_session', to: 'sessions#new_admin_session', as: 'new_admin_session'
  post '/sessions/new_admin_session', to: 'sessions#create_admin_session', as: 'admin_session'
  delete '/sessions', to: 'sessions#destroy'

  get 'teams/:id/answers/new', to: 'answers#new', as: 'new_answer'
  post '/teams/:id/answers', to: 'answers#create'
  
  get 'admins/:id/my_teams', to: 'admins#my_teams', as: 'my_teams'
end
  

app/models/user.rb
class User < ApplicationRecord
    has_many :requests, dependent: :destroy
    has_many :teams, through: :requests
    has_many :answers
    enum role: [:standard_user, :gold_user]
    # after_initialize :set_default_role, :if => :new_record?

    validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    has_secure_password
    has_one_attached :avatar 

    # def set_default_role
    #     self.role ||= :student
    # end


    # find answers according to team / question
    #self.answers.where(Question.find(self.question_id) == team.question)
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamBuilderProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">
  </head>
<body>
  <div class="page">
  <div class="topnav">
      <a class="active" href="/teams">Home</a>
      
      <% if current_user.class == Admin %> 
      <%= link_to 'My Teams', "/admins/#{session[:admin_id]}/my_teams"%>
      <%end%>
      
      <%if current_user.class == User %>
        <%= link_to 'Lucky Team', "/teams/#{session[:team_ids].sample}"%>
      <%end%>

      <%if current_user.class == Admin %>
        <%= link_to 'Create Team', new_team_path%>
      <%end%>
 
      <% if current_user.class == User %> 
      <p><%= link_to 'Log out', sessions_path, method: :delete %></p>
          <p><%= link_to "#{current_user.name}", "/users/#{session[:user_id]}"%></p>
      <% elsif current_user.class == Admin %>
      <p><%= link_to 'Log out', sessions_path, method: :delete %></p>
          <p><%= link_to "#{current_user.name}", "/admins/#{session[:admin_id]}"%></p>
      <% else %>
          <%= link_to 'Log in', new_session_path%>
      <% end %>

   </div>

  
      
    <% if flash[:notice]%>
    <h4><%= flash[:notcie] %></h4>
    <%end%>
    <%= yield %>
    


  
      <div class="footer">
      
        <p> Made by Louis and Haami 2019 </p>
      </div>
    </div>


    </body>
</html>